"""arcade — match manager for the AI Agent Arcade.

Not a game engine: it never validates moves (ref.py owns that). It allocates
match dirs, deploys the engine runtime into the live dir, tracks match.json,
and archives finished games. See arcade/docs/cli-brief.md.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

DEPLOY_FILES = [
    "tui_dots.py", "arcade_panel.py", "chat_tui.py", "chat.py",
    "game_cli.py", "game.sh", "ref.py", "FACILITATOR.md",
    "director_keeper.sh", "approver.sh", "eval.py",
]
DEPLOY_FILES_XIANGQI = [
    "tui_xiangqi.py", "chat_tui.py", "chat.py",
    "game_xq_cli.py", "game_xq.sh", "ref_xq.py", "xiangqi.py", "FACILITATOR_XQ.md",
    "director_keeper.sh",
]
DEPLOY_FILES_COREWAR = [
    "corewar.py", "ref_cw.py", "game_cw_cli.py", "game_cw.sh", "tui_corewar.py",
    "chat.py", "chat_tui.py", "director_keeper.sh", "FACILITATOR_CW.md",
]
# director_keeper.sh keeps its filename (2e rename touched its prompts/log
# text and env var only, not the file itself -- see docs/design-history.md
# §14) so DEPLOY_FILES above is unchanged by the HOST rename.
# Per-game deploy list. chess keeps its historical bare DEPLOY_FILES name (and
# behavior) so existing callers/tests are unaffected; GAME_DEPLOY_FILES is
# the lookup cmd_start actually uses, keyed by the `game` positional.
GAME_DEPLOY_FILES = {"chess": DEPLOY_FILES, "xiangqi": DEPLOY_FILES_XIANGQI,
                     "corewar": DEPLOY_FILES_COREWAR}
# Live-dir file lifecycle. See docs/cli-brief.md.
# PER-MATCH: belongs to one game; `arcade start` snapshots then clears it.
PER_MATCH_TRUNCATE = ["chat.log", "banner.txt", "eval.log", "keeper.log", "ctl"]
# host.txt is the HOST-renamed successor to director.txt (docs/design-history.md
# §14); PER_MATCH_UNLINK clears whichever one a given engine build actually
# wrote, so an older deployed copy that still writes director.txt is cleaned
# up the same as a fresh host.txt.
# stage_log.txt (every submit()/stage_special() a player ever made, durable
# beyond pending.txt's churn) and menu.txt (the ply the numbered legal-move
# menu was last printed at, for submit-by-number stale-check) are the seat-UX
# round's two new runtime files (engine/game_cli.py, game_xq_cli.py) -- same
# PER-MATCH lifecycle class as pending.txt/result.txt: unlinked, not
# truncated, because nothing tails them (unlike chat.log/eval.log/etc, no
# running pane holds them open) and their *absence* is already the "nothing
# on record" signal both files' own readers already treat it as
# (_last_stage()/read_menu() both check .exists() first). Left OUT of a fresh
# start, this is exactly the pairing-state-bleed bug class from game 6: the
# next match's very first `status` could resolve a player's "last submission"
# against a dead match's ply and misreport APPLIED/REJECTED.
PER_MATCH_UNLINK = ["pending.txt", "result.txt", "draw_offer.txt", "TAMPER.txt", "roles.txt",
                     "host.txt", "director.txt", "stage_log.txt", "menu.txt"]
PER_MATCH_GLOBS = [".stalls_*", ".last_*", ".prompt_out", ".ref_err", ".illegal"]
# SERIES: cumulative across matches, never cleared. Names are in every line,
# so it is pairing-agnostic storage read through a pairing filter (head_to_head).
SERIES_FILES = ["results.txt"]
# Rewritten every start from match.json (not "reset" — replaced):
#   names.txt seats.txt roles.txt series.txt banner.txt host.txt
# Regenerated by ref init: moves.txt fen.txt board.txt
# Cleared (PER_MATCH_UNLINK) but NOT rewritten by `arcade start` -- created
# fresh by game_cli.py/game_xq_cli.py themselves on first use, same as
# pending.txt: stage_log.txt menu.txt
# Untouched (operator/display state, not match state): mode.txt size.txt
#   panes.txt .chatpane .dotspane .classicpane .newpane .panelpanes backup/
#   and every deployed engine script.

# DIRECTOR stays reserved forever alongside HOST: old archives (matches 1-6)
# and any not-yet-redeployed live room still use the DIRECTOR identity.
# BLUE is reserved with the other seat-color words now that corewar's second
# seat is labelled "blue" (GAME_COLORS).
RESERVED_NAMES = {"ARCADE", "REFEREE", "DIRECTOR", "HOST", "WHITE", "BLACK", "BLUE"}

# menu.txt is deliberately NOT archived: it is ephemeral client-side UI state
# (which ply a menu was printed at, for stale-number detection) with no
# evidentiary value about what happened in the match -- unlike stage_log.txt,
# which is precisely the audit trail (staged vs. applied) the receipt feature
# exists to create.
ARCHIVE_FILES = ["moves.txt", "fen.txt", "chat.log", "results.txt", "names.txt",
                  "seats.txt", "roles.txt", "banner.txt", "series.txt",
                  "result.txt", "eval.log", "keeper.log", "host.txt", "director.txt",
                  "stage_log.txt"]
# Per-game archive extras, keyed by game. Corewar's staged warriors ARE the
# match evidence: the transcript's LOAD lines carry only their sha256, so an
# archive without warriors/A.red + warriors/B.red can never be re-verified
# (ref_cw.py verify re-simulates from the locked warrior sources), and
# battle.json is the renderer's cache of that same battle. Nested paths
# (warriors/...) are why the copy loop mkdirs parents. chess/xiangqi have
# no extras -- their evidence is flat and already in ARCHIVE_FILES.
GAME_ARCHIVE_EXTRA = {"corewar": ["warriors/A.red", "warriors/B.red", "battle.json"]}
DEFAULT_LIVE = Path("/tmp/chess")
GAME_DEFAULT_LIVE = {"chess": DEFAULT_LIVE, "xiangqi": Path("/tmp/xiangqi"),
                     "corewar": Path("/tmp/corewar")}
# ref script + `uv run --with` packages per game. xiangqi.py/ref_xq.py are
# stdlib-only (unlike chess.py, a PyPI package ref.py needs `--with chess` for).
# corewar.py/ref_cw.py are stdlib-only too (own MARS, no pMARS dependency).
GAME_REF_SCRIPT = {"chess": "ref.py", "xiangqi": "ref_xq.py", "corewar": "ref_cw.py"}
GAME_UV_WITH = {"chess": ["chess"], "xiangqi": [], "corewar": []}
# Player-facing wrapper script + facilitator briefing, per game.
GAME_SCRIPT = {"chess": "game.sh", "xiangqi": "game_xq.sh", "corewar": "game_cw.sh"}
GAME_FACILITATOR = {"chess": "FACILITATOR.md", "xiangqi": "FACILITATOR_XQ.md",
                    "corewar": "FACILITATOR_CW.md"}
# Seat color labels: xiangqi's first mover is "red" (chess.py's "white" seat
# internally -- see ref_xq.py's own check_author() comment on that mapping).
# corewar's seats are "red"/"blue" over the same internal white/black keys.
GAME_COLORS = {"chess": ("white", "black"), "xiangqi": ("red", "black"),
               "corewar": ("red", "blue")}
# Conventional seat-flag spellings per game (every spelling parses for every
# game -- shared argparse dests in build_parser); warn_seat_flag_mismatch
# notes the off-game spelling without refusing.
GAME_SEAT_FLAGS = {"chess": ("--white", "--black"), "xiangqi": ("--red", "--black"),
                   "corewar": ("--red", "--blue")}
MATCH_RE_PREFIX = "match-"


def default_live_for(game):
    return GAME_DEFAULT_LIVE.get(game, DEFAULT_LIVE)


def color_labels(game):
    return GAME_COLORS.get(game, ("white", "black"))


def find_arcade_root(start):
    """Nearest ancestor of `start` that looks like an arcade checkout.

    An arcade root holds both `engine/` (the runtime the CLI deploys) and
    `cli/` (this package's own project dir). Both are required so a stray
    `engine/` elsewhere on the path cannot be mistaken for the root.
    """
    for cand in (start, *start.parents):
        if (cand / "engine").is_dir() and (cand / "cli").is_dir():
            return cand
    return None


def default_root():
    """Where games/ and engine/ live, when no --root and no ARCADE_ROOT.

    Resolution order, so a fresh clone works with no configuration:
      1. $ARCADE_ROOT
      2. the arcade checkout containing this file (an editable/uv-run install
         keeps main.py inside the tree, which is the normal case)
      3. the arcade checkout containing $PWD (a non-editable `uv tool install`
         copies the package out of the tree, so the cwd is the only clue)
      4. $PWD, which then fails loudly on a missing engine/ rather than
         silently pointing at one particular machine's home directory
    """
    env = os.environ.get("ARCADE_ROOT")
    if env:
        return Path(env)
    here = Path(__file__).resolve()
    found = find_arcade_root(here.parent)
    if found:
        return found
    cwd = Path.cwd().resolve()
    return find_arcade_root(cwd) or cwd


def get_root(args):
    return Path(args.root) if getattr(args, "root", None) else default_root()


def get_live_dir(args):
    if getattr(args, "live_dir", None):
        return Path(args.live_dir)
    env = os.environ.get("ARCADE_LIVE")
    if env:
        return Path(env)
    return default_live_for(getattr(args, "game", None) or "chess")


def live_dir_explicit(args):
    """True if the live dir was actually chosen (flag or env), not defaulted."""
    return bool(getattr(args, "live_dir", None)) or bool(os.environ.get("ARCADE_LIVE"))


def games_dir_for(root, game):
    return root / "games" / game


def read_text(p, default=""):
    try:
        return p.read_text()
    except OSError:
        return default


# ---------------------------------------------------------------------------
# series (results.txt is cumulative and pairing-agnostic; every display of it
# must be filtered through head_to_head for the pairing actually on screen)

VALID_SCORES = ("1-0", "0-1", "1/2-1/2")


def parse_results(text):
    """[(white, score, black)] from `<WHITE> <SCORE> <BLACK>` lines; skips junk."""
    rows = []
    for ln in text.splitlines():
        p = ln.split()
        if len(p) == 3 and p[1] in VALID_SCORES:
            rows.append((p[0].upper(), p[1], p[2].upper()))
    return rows


def head_to_head(rows, a, b):
    """(wins_a, wins_b, draws, games) for the {a,b} pairing, order-insensitive:
    a line counts whichever colour each player held."""
    a, b = a.upper(), b.upper()
    wa = wb = dr = 0
    for white, score, black in rows:
        if {white, black} != {a, b}:
            continue
        if score == "1/2-1/2":
            dr += 1
        elif (score == "1-0") == (white == a):
            wa += 1
        else:
            wb += 1
    return wa, wb, dr, wa + wb + dr


def series_short(a, b, rec):
    wa, wb, dr, n = rec
    if not n:
        return "FIRST MEETING"
    tail = f", {dr} draw(s)" if dr else ""
    return f"{a} {wa}-{wb} {b} ({n} game(s){tail})"


# ---------------------------------------------------------------------------
# match.json helpers

def match_number(match_dir):
    try:
        return int(match_dir.name[len(MATCH_RE_PREFIX):])
    except ValueError:
        return None


def iter_matches(games_dir):
    """Yield (match_dir, data) for every match-NNN dir, sorted by number.

    A dir that looks like a match (matches the naming pattern) but has no
    readable match.json is skipped — loudly, since silently skipping it would
    let next_match_number() reuse its number and crash on mkdir later.
    """
    if not games_dir.exists():
        return
    dirs = [d for d in games_dir.iterdir() if d.is_dir() and d.name.startswith(MATCH_RE_PREFIX)]
    for d in sorted(dirs, key=lambda d: match_number(d) or 0):
        mj = d / "match.json"
        if not mj.exists():
            print(f"warning: {d} has no match.json — skipping, its number may be reused", file=sys.stderr)
            continue
        try:
            yield d, json.loads(mj.read_text())
        except json.JSONDecodeError as e:
            print(f"warning: {mj} is not valid JSON ({e}) — skipping, its number may be reused", file=sys.stderr)
            continue


def next_match_number(games_dir):
    nums = [match_number(d) for d, _ in iter_matches(games_dir)]
    nums = [n for n in nums if n is not None]
    return (max(nums) if nums else 0) + 1


def find_newest_match(games_dir, status=None):
    """Newest (highest-numbered) match dir, optionally filtered by status."""
    best = None
    for d, data in iter_matches(games_dir):
        if status is not None and data.get("status") != status:
            continue
        best = (d, data)
    return best


def resolved_live_dir(path):
    """Return a stable absolute spelling for live-dir identity checks."""
    try:
        return Path(path).expanduser().resolve()
    except (TypeError, OSError, RuntimeError):
        return None


def match_uses_live_dir(data, live):
    """Whether a match record is bound to the requested live directory."""
    recorded_live = resolved_live_dir(data.get("live_dir"))
    return recorded_live is not None and recorded_live == resolved_live_dir(live)


def find_live_matches_for_dir(root, live):
    """All live matches, across every game, bound to ``live``."""
    games_root = root / "games"
    if not games_root.exists():
        return []

    matches = []
    for games_dir in sorted(p for p in games_root.iterdir() if p.is_dir()):
        for match_dir, data in iter_matches(games_dir):
            if data.get("status") == "live" and match_uses_live_dir(data, live):
                matches.append((games_dir.name, match_dir, data))
    return matches


def write_match_json(match_dir, data):
    (match_dir / "match.json").write_text(json.dumps(data, indent=2) + "\n")


# ---------------------------------------------------------------------------
# start

def seat(agent):
    lowered = agent.lower()
    if lowered == "human" or lowered.startswith("human:"):
        name = agent[len("human:"):] if lowered.startswith("human:") else ""
        if not name:
            print("error: --white/--black human requires a name, e.g. human:ada", file=sys.stderr)
            sys.exit(1)
        if any(c.isspace() for c in name):
            print(f"error: human seat name {name!r} must not contain whitespace "
                  f"(names.txt is space-separated) — use human:adalovelace, not human:ada lovelace",
                  file=sys.stderr)
            sys.exit(1)
        return {"agent": "human", "name": name.upper()}
    return {"agent": agent, "name": agent.upper()}


def validate_seats(seats):
    """Two cheap refusals the reset/seeding scaffolding now depends on:
    identical names make seats.txt/roles.txt/role_of()/head_to_head() all
    ambiguous, and a reserved name would be misclassified by roles.txt (or
    could not be seat-checked at all)."""
    white_name, black_name = seats["white"]["name"], seats["black"]["name"]
    if white_name == black_name:
        print(f"error: white and black seat names are both {white_name!r} — "
              f"names must be distinct.", file=sys.stderr)
        sys.exit(1)
    for name in (white_name, black_name):
        if name in RESERVED_NAMES:
            print(f"error: {name!r} is a reserved name ({sorted(RESERVED_NAMES)}) — "
                  f"pick a different seat name.", file=sys.stderr)
            sys.exit(1)


def host_seat(agent):
    # CHESS_NAME=HOST is the fixed convention (FACILITATOR.md) — the room
    # always sees "HOST", regardless of which agent holds the seat. (2e
    # rename: this was DIRECTOR/"DIRECTOR" — see docs/design-history.md §14.
    # DIRECTOR stays reserved in RESERVED_NAMES for old archives.)
    return {"agent": agent, "name": "HOST"}


def host_prompt(data, live):
    white, black = data["seats"]["white"], data["seats"]["black"]
    # `data.get("host")` covers matches seated after the 2e rename;
    # `data.get("director")` is the fallback for older match.json files
    # written under the pre-rename schema (see docs/design-history.md §14).
    host = data.get("host") or data.get("director")
    game = data["game"]
    c1, c2 = color_labels(game)
    facilitator = GAME_FACILITATOR.get(game, "FACILITATOR.md")
    lines = []
    if host:
        lines.append(f"export CHESS_NAME={host['name']}")
    lines.append(f"cd {live}")
    lines.append(f"Read {live}/{facilitator} and follow it exactly.")
    lines.append(
        f"You are hosting match {data['match']} ({game}): "
        f"{white['name']} ({c1}, agent {white['agent']}) vs "
        f"{black['name']} ({c2}, agent {black['agent']})."
    )
    return "\n".join(lines)


def human_runbook(seat_data, color, live, script="game.sh"):
    name = seat_data["name"]
    lines = [
        f"# You are {name} ({color}). Play with:",
        f"export CHESS_NAME={name}",
        f"bash {live}/{script} show",
        f"bash {live}/{script} submit '<move>'",
        f"bash {live}/{script} say '<message>'",
        f"bash {live}/{script} status       # one-shot recovery: ply/turn/last move/pending",
        f"bash {live}/{script} history      # numbered move list",
        f"bash {live}/{script} await-turn   # block until it's your move, then show",
    ]
    return "\n".join(lines)


def print_runbook(data, live, backup_dir=None):
    white, black = data["seats"]["white"], data["seats"]["black"]
    host = data.get("host") or data.get("director")
    game = data["game"]
    c1, c2 = color_labels(game)
    script = GAME_SCRIPT.get(game, "game.sh")
    ref_script = GAME_REF_SCRIPT.get(game, "ref.py")
    facilitator = GAME_FACILITATOR.get(game, "FACILITATOR.md")
    print(f"--- match-{data['match']:03d} runbook ({game}) ---")
    print()
    if backup_dir:
        print(f"Note: a prior moves.txt/fen.txt was snapshotted to {backup_dir} before {ref_script} init.")
        print()
    print("Seat the players (herdr):")
    for color, s in ((c1, white), (c2, black)):
        if s["agent"] == "human":
            print()
            print(human_runbook(s, color, live, script))
            print()
        else:
            print(f"  herdr agent start {s['agent']} --kind {s['agent']} --pane <id>   # {color}, cwd {live}")
    if host:
        print(f"  herdr agent start {host['agent']} --kind {host['agent']} --pane <id>   # host, cwd {live}")
    print()
    if host:
        print("Host seating prompt:")
        print(host_prompt(data, live))
        print()
    kimi_seats = [s["agent"] for s in (white, black, host or {}) if s and s.get("agent") == "kimi"]
    if kimi_seats and game == "chess":
        # approver.sh is only deployed for chess (see DEPLOY_FILES) -- xiangqi
        # has no approver.sh in its deploy set yet.
        print(f"Note: kimi seat(s) need the approver running: (cd {live} && ./approver.sh &)")
    print(f"Host pre-flight: verify panes/names per {facilitator} before the first move.")


def run_ref_init(live, force, game="chess"):
    """Initialize match state in `live` by shelling out to the deployed
    referee script (ref.py for chess, ref_xq.py for xiangqi, ref_cw.py for
    corewar), always passing ARCADE_LIVE explicitly in the subprocess
    environment.

    Every engine script deployed into a live dir — the referee included —
    now resolves `D = Path(os.environ.get('ARCADE_LIVE', '/tmp/<game>'))` at
    import time instead of hardcoding a default live dir, so setting
    ARCADE_LIVE on the subprocess (rather than relying on it being inherited
    from our own environment, which it may not be) reaches any live dir, not
    just the default. This used to be a live hazard: a copy of ref.py shelled
    into from a scratch live dir would silently reinitialize the real
    /tmp/chess instead, which is what wiped a live game's moves.txt/fen.txt
    during a previous hardening round (design-history.md §10) — that vector
    is closed now that the engine itself honors ARCADE_LIVE.
    """
    ref_script = GAME_REF_SCRIPT.get(game, "ref.py")
    with_args = []
    for pkg in GAME_UV_WITH.get(game, []):
        with_args += ["--with", pkg]
    cmd = ["uv", "run", "--quiet", *with_args, "python", str(live / ref_script), "init"]
    if force:
        cmd.append("--force")
    env = {**os.environ, "ARCADE_LIVE": str(live)}
    subprocess.run(cmd, cwd=live, env=env, check=True)


# Every file PER_MATCH_TRUNCATE/PER_MATCH_UNLINK is about to clear belongs
# here too -- snapshot_pre_start's docstring says "every non-empty file",
# not "every evidence-worthy file"; that is ARCHIVE_FILES's job, a narrower
# and separate list. menu.txt has no archival value (see ARCHIVE_FILES's
# comment) but is cheap to snapshot and the invariant is meant to be
# unconditional, so it is included here anyway.
SNAPSHOT_FILES = ["moves.txt", "fen.txt", "chat.log", "banner.txt", "results.txt",
                   "names.txt", "seats.txt", "eval.log", "keeper.log", "result.txt",
                   "stage_log.txt", "menu.txt"]


def snapshot_pre_start(live, newest):
    """Copy every non-empty file `start` is about to overwrite or clear into
    <live>/backup/<name>.<tag>.<ext>. Returns the backup dir, or None if
    there was nothing to save.

    The gate is per file, not "moves.txt is non-empty": a finished match with
    an empty moves.txt but a non-empty chat.log must still snapshot the chat
    log, now that reset_room() truncates it. Snapshot failure is fatal —
    refusing to start beats clearing without a copy.
    """
    tag = f"match-{newest[1]['match']:03d}" if newest else str(int(time.time()))
    backup_dir = None
    for fn in SNAPSHOT_FILES:
        src = live / fn
        try:
            if not (src.exists() and src.read_text().strip()):
                continue
        except OSError as e:
            print(f"error: could not read {src} to snapshot it before start: {e}", file=sys.stderr)
            sys.exit(1)
        if backup_dir is None:
            backup_dir = live / "backup"
            backup_dir.mkdir(parents=True, exist_ok=True)
        stem, dot, ext = fn.partition(".")
        dest = backup_dir / f"{stem}.{tag}.{ext}" if dot else backup_dir / f"{fn}.{tag}"
        try:
            shutil.copy2(src, dest)
        except OSError as e:
            print(f"error: failed to snapshot {src} to {dest}: {e}", file=sys.stderr)
            sys.exit(1)
    return backup_dir


def reset_room(live):
    """Clear per-match social/broadcast/runtime state. Call ONLY after a
    successful ref init and only after snapshot_pre_start has run.

    Truncate-vs-unlink is deliberate: chat.log/banner.txt/eval.log/
    keeper.log/ctl are tailed by running panes, so they are emptied in place,
    never unlinked. The ref-owned flag files are unlinked because their
    *existence* is the signal.
    """
    for fn in PER_MATCH_TRUNCATE:
        p = live / fn
        if p.exists():
            p.write_text("")
    for fn in PER_MATCH_UNLINK:
        (live / fn).unlink(missing_ok=True)
    for pat in PER_MATCH_GLOBS:
        for p in live.glob(pat):
            if p.is_file():
                p.unlink(missing_ok=True)


def cmd_start(args):
    root = get_root(args)
    live = get_live_dir(args)
    engine = root / "engine"
    games_dir = games_dir_for(root, args.game)

    game_default_live = default_live_for(args.game)
    if live != game_default_live:
        # Historically this warned that the override wouldn't hold at all
        # (design-history.md §10) — engine scripts hardcoded /tmp/chess and
        # ignored env/cwd. Fixed: every engine script now reads ARCADE_LIVE
        # at import time, and run_ref_init passes it explicitly to the
        # referee's subprocess. The remaining gap is scripts run by hand
        # later (e.g. a seated agent's shell) — those only follow `live` if
        # ARCADE_LIVE is set in *their* environment too.
        print(f"note: live dir is {live}, not {game_default_live} — this init run honors it. "
              f"If you run any deployed engine script by hand afterward, export "
              f"ARCADE_LIVE={live} first so it resolves the same dir.", file=sys.stderr)
    elif os.environ.get("ARCADE_ROOT") and not live_dir_explicit(args):
        # Incident-driven: ARCADE_ROOT overrides the games root to a scratch
        # tree, but the live dir silently defaulted to the real /tmp/chess —
        # this is exactly the vector that wiped a live game's moves.txt/fen.txt
        # during verification. Always a mistake; no --force override.
        print(f"refusing: ARCADE_ROOT={os.environ['ARCADE_ROOT']} overrides the games root to "
              f"{root}, but no --live-dir/ARCADE_LIVE was given so the live dir defaulted to "
              f"{game_default_live} (production) — scratch games root with production live dir. "
              f"Pass --live-dir or set ARCADE_LIVE.", file=sys.stderr)
        sys.exit(1)

    # Deploy preflight (before step 4): every file the deploy loop (step 5)
    # copies must exist under engine/ BEFORE start makes any filesystem
    # change. Without this a missing engine file surfaces as a copy2
    # traceback AFTER match_dir was created, orphaning a match.json-less
    # match dir that hard-blocks every later `arcade start` ("already
    # exists (stale or corrupt match dir?)") — same trap class as the
    # seat-validation path step 6 cleans up after.
    deploy_files = GAME_DEPLOY_FILES.get(args.game, DEPLOY_FILES)
    missing = [fn for fn in deploy_files if not (engine / fn).is_file()]
    if missing:
        print(f"error: cannot start {args.game}: engine dir {engine} is missing "
              f"{len(missing)} deploy file(s): {', '.join(missing)} — refusing; "
              f"no match dir was created.", file=sys.stderr)
        sys.exit(1)

    games_dir.mkdir(parents=True, exist_ok=True)

    # The guard is about the newest match dir's status, not moves.txt content:
    # archive() flips status to complete but never touches the live dir, so a
    # non-empty moves.txt left over from a *finished* match is normal, not a
    # game in progress. Only a still-"live" newest match blocks a fresh start.
    newest = find_newest_match(games_dir)
    if newest and newest[1].get("status") == "live" and not args.force:
        d, _ = newest
        print(f"refusing: {d.name} is still live — pass --force to override.", file=sys.stderr)
        sys.exit(1)
    # Either the newest match is complete/abandoned (its log is legitimately
    # finished) or there's no prior match at all — either way ref.py init
    # doesn't need the *operator* to have passed --force to proceed cleanly.
    force_init = True

    # Concurrent `arcade start` invocations racing on next_match_number()/mkdir
    # is a known gap — single-operator tool, not guarded against here.
    num = next_match_number(games_dir)
    match_dir = games_dir / f"{MATCH_RE_PREFIX}{num:03d}"
    try:
        match_dir.mkdir(parents=True)
    except FileExistsError:
        print(f"error: {match_dir} already exists (stale or corrupt match dir?) — "
              f"resolve it by hand before retrying.", file=sys.stderr)
        sys.exit(1)

    live.mkdir(parents=True, exist_ok=True)
    for fn in deploy_files:
        shutil.copy2(engine / fn, live / fn)

    # Step 6: build + validate seats before any identity/room mutation, so a
    # bad seat name fails loudly instead of clearing state on the way out.
    # match_dir (step 4) and the deployed engine files (step 5) already
    # exist at this point -- validate_seats's sys.exit(1) would otherwise
    # leave a match.json-less match_dir behind that hard-blocks every later
    # `arcade start` ("already exists"), so clean it up on this path too,
    # mirroring the failed-ref-init cleanup below.
    seats = {"white": seat(args.white), "black": seat(args.black)}
    try:
        validate_seats(seats)
    except SystemExit:
        shutil.rmtree(match_dir, ignore_errors=True)
        raise
    W, B = seats["white"]["name"], seats["black"]["name"]

    # Step 7: unarchived-match warning. Not a refusal — an operator who
    # forgets `arcade archive` should still be able to seat the next match;
    # the snapshot (step 8) is what makes that safe.
    if newest and not (newest[0] / "chat.log").exists() and (live / "chat.log").exists():
        print(f"note: {newest[0].name} was never archived (no chat.log in its match dir). "
              f"The live room is being reset for the new match; its contents are "
              f"snapshotted to {live}/backup/. Run `arcade archive` first next time.",
              file=sys.stderr)

    # Step 8: snapshot everything the reset below is about to overwrite/clear.
    backup_dir = snapshot_pre_start(live, newest)

    # Step 9: identity files, written fresh every start — must precede init
    # because render() reads names.txt (after the §7 identity-leak fix).
    (live / "names.txt").write_text(f"{W} {B}\n")
    # seats.txt is the seat-bound identity contract game_cli.py/game_xq_cli.py
    # (via chat.require_seated()) hard-refuse submit/resign/offer-draw/accept-draw
    # against: `<NAME> white` / `<NAME> black`, one line each. Game-5 retro fix --
    # a wrong/unset identity used to stage silently and get discarded later.
    (live / "seats.txt").write_text(f"{W} white\n{B} black\n")

    try:
        run_ref_init(live, force_init, game=args.game)
    except subprocess.CalledProcessError as e:
        shutil.rmtree(match_dir, ignore_errors=True)
        print(f"error: match init failed (exit {e.returncode}) — no match dir was created. "
              f"See any output above for why.", file=sys.stderr)
        sys.exit(e.returncode or 1)

    # Step 11: clear per-match social/broadcast/runtime state, now that init
    # has succeeded. --keep-room skips this (re-seating an interrupted match,
    # or dev iteration) but not the snapshot above.
    if not getattr(args, 'keep_room', False):
        reset_room(live)

    # roles.txt removes the stale-role leak: chat.roles() overrides role_of(),
    # so a leftover line from a departed player would misclassify the new
    # seats. Written fresh every start (regardless of --keep-room), always
    # AFTER reset_room: roles.txt is also in PER_MATCH_UNLINK (its *absence*
    # doubles as the reset signal for an older deployed engine build that
    # still reads it that way), so writing it before the reset would just
    # have it deleted again.
    (live / "roles.txt").write_text(
        f"{W} white\n{B} black\nARCADE facilitator\nREFEREE facilitator\n"
        f"DIRECTOR facilitator\nHOST facilitator\n")

    # host.txt is the herdr agent name game.sh/game_xq.sh auto-poke after a
    # staging verb succeeds (2e rename: was director.txt — see
    # docs/design-history.md §14; game.sh/game_xq.sh fall back to a stale
    # director.txt from an older deploy if host.txt is absent). Same
    # lifecycle as roles.txt: in PER_MATCH_UNLINK (so a hostless start clears
    # a stale one via reset_room above) and rewritten fresh here, after the
    # reset, when a host is seated this match.
    if args.host:
        (live / "host.txt").write_text(args.host.lower() + "\n")

    # Step 12: series.txt + seeded banner.txt + seeded chat.log, all
    # pairing-filtered against the cumulative results.txt ledger.
    rows = parse_results(read_text(live / "results.txt"))
    rec = head_to_head(rows, W, B)
    wa, wb, _dr, n = rec
    short = series_short(W, B, rec)
    (live / "series.txt").write_text(short + "\n")

    c1, c2 = color_labels(args.game)
    tag = "FIRST MEETING" if not n else f"{W} {wa}-{wb} {B}"
    (live / "banner.txt").write_text(f"GAME {num} — {W} vs {B} — {tag}\n")

    if not getattr(args, 'keep_room', False):
        line = (f"match-{num:03d} opens: {W} ({c1.title()}) vs {B} ({c2.title()}). "
                f"Fresh room — the previous match's chat is archived. "
                f"Series, this pairing: {short}.")
        (live / "chat.log").write_text(f"{int(time.time())}\tARCADE\t{line}\n")

    # match.json is only written once init has actually succeeded, so a failed
    # start never leaves an orphaned match dir behind.
    data = {
        "game": args.game,
        "match": num,
        "started": datetime.now().isoformat(timespec="seconds"),
        "seats": seats,
        "host": host_seat(args.host) if args.host else None,
        "live_dir": str(live),
        "status": "live",
        "result": None,
        "ended": None,
    }
    write_match_json(match_dir, data)

    print_runbook(data, live, backup_dir)


# ---------------------------------------------------------------------------
# status

def cmd_status(args):
    root = get_root(args)
    live = get_live_dir(args)
    games_dir = games_dir_for(root, args.game)

    moves = read_text(live / "moves.txt").split()
    ply = len(moves)
    side = "white" if ply % 2 == 0 else "black"
    last_san = moves[-1] if moves else None
    fen = read_text(live / "fen.txt").strip() or None
    pending_raw = read_text(live / "pending.txt").strip()
    if pending_raw and "\t" in pending_raw:
        who, san = pending_raw.split("\t", 1)
        pending = f"{san} (staged by {who})"
    else:
        pending = pending_raw or None
    names = read_text(live / "names.txt").split()

    match = find_newest_match(games_dir, status="live") or find_newest_match(games_dir)
    results_text = read_text(live / "results.txt")
    results_lines = [l for l in results_text.splitlines() if l.strip()]

    print(f"live dir: {live}")
    if match:
        d, data = match
        print(f"match: {d.name} ({data['status']}) — {data['seats']['white']['name']} vs "
              f"{data['seats']['black']['name']}")
    else:
        print("match: (no match.json found)")
    print(f"ply: {ply}  to move: {side}")
    print(f"last move: {last_san or '(none)'}")
    print(f"fen: {fen or '(missing)'}")
    print(f"pending: {pending or '(none staged)'}")
    if names:
        print(f"names.txt: {' '.join(names)}")

    # series is always pairing-filtered — printing the last raw results.txt
    # line here is exactly the reported bug (it names the *previous*
    # pairing). Pairing comes from the resolved match's match.json seats,
    # falling back to names.txt when no match.json was found.
    if match:
        pw = match[1]["seats"]["white"]["name"]
        pb = match[1]["seats"]["black"]["name"]
    elif len(names) == 2:
        pw, pb = names[0], names[1]
    else:
        pw = pb = None
    if pw and pb:
        rec = head_to_head(parse_results(results_text), pw, pb)
        print(f"series ({pw} vs {pb}): {series_short(pw, pb, rec)}   "
              f"[results.txt: {len(results_lines)} line(s) total]")
    else:
        print("series: (no pairing known)")


# ---------------------------------------------------------------------------
# archive

def cmd_archive(args):
    root = get_root(args)
    live = resolved_live_dir(get_live_dir(args))
    game = getattr(args, "game", None)

    if game is None:
        # With no game selector, the live-dir binding is the only safe source
        # of game identity. Never guess from whichever game's match number is
        # newest: that can copy one game's runtime over another game's archive.
        matches = find_live_matches_for_dir(root, live)
        if not matches:
            print(f"no live match for {live} across {root / 'games'}; "
                  f"pass --game <game> only to re-archive a completed match "
                  f"whose live_dir is {live}", file=sys.stderr)
            sys.exit(1)
        if len(matches) > 1:
            found = ", ".join(f"{found_game}/{match_dir.name}"
                              for found_game, match_dir, _ in matches)
            print(f"multiple live matches for {live}: {found}; "
                  f"pass --game <game> to select one", file=sys.stderr)
            sys.exit(1)
        _, match_dir, data = matches[0]
    else:
        games_dir = games_dir_for(root, game)

        # Preserve the explicit-game behavior: prefer the newest live match,
        # then permit an idempotent re-archive of the newest completed match.
        # In both cases, verify the record's live-dir binding before any copy.
        selected = find_newest_match(games_dir, status="live")
        if selected:
            match_dir, data = selected
            if not match_uses_live_dir(data, live):
                recorded_live = resolved_live_dir(data.get("live_dir"))
                other = recorded_live or data.get("live_dir") or "(missing live_dir)"
                print(f"--game {game} selected live match {match_dir.name} for {other}; "
                      f"requested live dir is {live} — refusing cross-game archive.",
                      file=sys.stderr)
                sys.exit(1)
        else:
            selected = find_newest_match(games_dir)
            if not selected:
                print(f"no match found under {games_dir}", file=sys.stderr)
                sys.exit(1)
            match_dir, data = selected
            if not match_uses_live_dir(data, live):
                recorded_live = resolved_live_dir(data.get("live_dir"))
                other = recorded_live or data.get("live_dir") or "(missing live_dir)"
                print(f"no live match for {live}; --game {game}'s newest match belongs "
                      f"to {other} — refusing cross-game archive.", file=sys.stderr)
                sys.exit(1)

    # `game` is None on the inferred path above (the tuple unpack there
    # discards it), so fall back to the match record's own game field.
    archive_game = game or data.get("game")
    for fn in ARCHIVE_FILES + GAME_ARCHIVE_EXTRA.get(archive_game, []):
        src = live / fn
        if src.exists():
            dest = match_dir / fn
            dest.parent.mkdir(parents=True, exist_ok=True)  # nested extras (warriors/...)
            shutil.copy2(src, dest)

    result = args.result
    if not result:
        lines = [l for l in read_text(live / "results.txt").splitlines() if l.strip()]
        result = lines[-1] if lines else None

    data["status"] = "complete"
    data["result"] = result
    data["ended"] = datetime.now().isoformat(timespec="seconds")
    write_match_json(match_dir, data)

    print(f"archived {match_dir.name}: result={result!r}")


# ---------------------------------------------------------------------------
# results

def cmd_results(args):
    root = get_root(args)
    games_root = root / "games"
    if not games_root.exists():
        print("no games directory found")
        return

    pairing = None
    if getattr(args, "pairing", None):
        pairing = {args.pairing[0].upper(), args.pairing[1].upper()}

    for game_dir in sorted(p for p in games_root.iterdir() if p.is_dir()):
        matches = list(iter_matches(game_dir))
        if pairing:
            matches = [(d, data) for d, data in matches
                       if {data["seats"]["white"]["name"], data["seats"]["black"]["name"]} == pairing]
        if not matches:
            continue
        print(f"== {game_dir.name} ==")
        tally, draws, pending = {}, 0, 0
        # Per-pairing grouping is the default (not opt-in): with rotating
        # players an ungrouped "series" number is meaningless. Key by
        # frozenset({white, black}) so colour doesn't split a pairing in two.
        by_pairing = {}
        for d, data in matches:
            white = data["seats"]["white"]["name"]
            black = data["seats"]["black"]["name"]
            result = data.get("result") or "(pending)"
            print(f"  {d.name}  {white} vs {black}  [{data['status']}]  {result}")
            r = data.get("result") or ""
            score = r.split()[1] if len(r.split()) > 1 else ""
            by_pairing.setdefault(frozenset((white, black)), []).append((white, score, black))
            if score == "1-0":
                tally[white] = tally.get(white, 0) + 1
            elif score == "0-1":
                tally[black] = tally.get(black, 0) + 1
            elif score == "1/2-1/2":
                draws += 1
            else:
                pending += 1

        if by_pairing:
            print("  head-to-head:")
            def sort_key(item):
                key, rows = item
                decided = sum(1 for _, s, _ in rows if s in VALID_SCORES)
                return (-decided, sorted(key))
            for key, rows in sorted(by_pairing.items(), key=sort_key):
                a, b = sorted(key)
                decided_rows = [(w, s, bl) for w, s, bl in rows if s in VALID_SCORES]
                pending_n = len(rows) - len(decided_rows)
                summary = series_short(a, b, head_to_head(decided_rows, a, b))
                if pending_n:
                    summary += f" ({pending_n} pending)"
                print(f"    {a} vs {b}:  {summary}")

        # Per-pairing grouping replaces the ungrouped all-time line when a
        # --pairing filter is active — with one pairing on screen the
        # head-to-head block above already says everything the all-time
        # line would.
        if not pairing and (tally or draws or pending):
            series = "  ".join(f"{name} {wins}" for name, wins in sorted(tally.items(), key=lambda kv: -kv[1]))
            extra = []
            if draws:
                extra.append(f"{draws} draw(s)")
            if pending:
                extra.append(f"{pending} pending/undecided")
            tail = ("  " + "  ".join(extra)) if extra else ""
            print(f"  all-time: {series}{tail}")


# ---------------------------------------------------------------------------
# prompt host

def cmd_prompt_host(args):
    root = get_root(args)
    games_dir = games_dir_for(root, args.game)
    match = find_newest_match(games_dir)
    if not match:
        print(f"no match found under {games_dir}", file=sys.stderr)
        sys.exit(1)
    _, data = match
    print(host_prompt(data, Path(data["live_dir"])))


# ---------------------------------------------------------------------------
# CLI wiring

def build_parser():
    # `--live-dir` needs to work both before and after the subcommand name
    # (`arcade --live-dir X status` and `arcade status --live-dir X`). A
    # subparser replaces the whole namespace with a fresh one on its own
    # defaults and then copies it onto the parent — so if the subparser's
    # copy also defaults live_dir to None, it silently clobbers a value set
    # at the top level. default=SUPPRESS keeps the attribute out of that
    # fresh namespace when the flag wasn't given at the subcommand level, so
    # the top-level value (if any) survives instead of being overwritten.
    live_dir_help = "live runtime dir (default: $ARCADE_LIVE or /tmp/chess)"

    p = argparse.ArgumentParser(prog="arcade", description="Match manager for the AI Agent Arcade.")
    p.add_argument("--live-dir", help=live_dir_help)
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("start", help="allocate + deploy a new match")
    s.add_argument("--live-dir", help=live_dir_help, default=argparse.SUPPRESS)
    s.add_argument("game")
    # --red is an alias for --white (same dest): both name the first-mover
    # seat -- chess calls it white, xiangqi and corewar call it red, but
    # internally (match.json, host_prompt, print_runbook) it's the same
    # "white" key throughout, matching ref_xq.py's own white<->red seat
    # mapping. Either spelling works for any game (main() warns, doesn't
    # refuse, if the off-game spelling is used -- see the seat-flag mismatch
    # note in warn_seat_flag_mismatch).
    s.add_argument("--white", "--red", dest="white", required=True,
                    help="first-mover seat: chess calls this --white, xiangqi/corewar call it "
                         "--red (same flag; either spelling is accepted for any game)")
    # --blue is an alias for --black (same dest, same pattern as
    # --white/--red above): corewar's second seat is "blue", internally the
    # same "black" key everywhere.
    s.add_argument("--black", "--blue", dest="black", required=True,
                    help="second seat: chess/xiangqi call this --black, corewar calls it --blue "
                         "(same flag; either spelling is accepted for any game)")
    # --director is the pre-2e-rename spelling, kept working forever (same
    # dest pattern as --white/--red above): the seat is HOST everywhere
    # forward-looking now (docs/design-history.md §14), --host is what the
    # runbook and docs show, but a caller/script still using --director must
    # not break.
    s.add_argument("--host", "--director", dest="host",
                    help="booth/host seat's herdr agent; --director is a back-compat alias")
    s.add_argument("--force", action="store_true")
    s.add_argument("--keep-room", action="store_true", dest="keep_room",
                    help="skip clearing chat.log/eval.log/keeper.log/ctl (identity files, "
                         "series.txt and banner.txt are still rewritten); does not skip the "
                         "pre-start snapshot")
    s.set_defaults(func=cmd_start)

    st = sub.add_parser("status", help="show live match status")
    st.add_argument("--live-dir", help=live_dir_help, default=argparse.SUPPRESS)
    st.add_argument("--game", default="chess")
    st.set_defaults(func=cmd_status)

    a = sub.add_parser("archive", help="archive the live match into its match dir")
    a.add_argument("--live-dir", help=live_dir_help, default=argparse.SUPPRESS)
    a.add_argument("--game")
    a.add_argument("--result")
    a.set_defaults(func=cmd_archive)

    r = sub.add_parser("results", help="series table across all matches")
    r.add_argument("--pairing", nargs=2, metavar=("A", "B"),
                    help="restrict the match listing and head-to-head block to this "
                         "pairing (order-insensitive, case-insensitive) and suppress "
                         "the all-time line")
    r.set_defaults(func=cmd_results)

    pr = sub.add_parser("prompt", help="print prompts")
    pr_sub = pr.add_subparsers(dest="prompt_command", required=True)
    # "director" is kept as an alias (2e rename, same back-compat spirit as
    # --host/--director above) so an existing `arcade prompt director` caller
    # keeps working; "host" is the name docs/runbooks show going forward.
    prd = pr_sub.add_parser("host", aliases=["director"], help="print the host seating prompt")
    prd.add_argument("--game", default="chess")
    prd.set_defaults(func=cmd_prompt_host)

    return p


def warn_seat_flag_mismatch(args, argv):
    """--white/--red share one dest and --black/--blue share another (see
    build_parser) so `arcade start chess --red kimi` parses silently -- cheap
    enough to just note the off-game spelling was used and move on, not worth
    a hard refusal over. Conventional spellings per game: GAME_SEAT_FLAGS."""
    if getattr(args, "command", None) != "start":
        return
    tokens = sys.argv[1:] if argv is None else argv
    first, second = GAME_SEAT_FLAGS.get(args.game, ("--white", "--black"))
    if "--red" in tokens and first != "--red":
        print(f"note: --red is xiangqi/corewar's spelling of the first-mover seat flag; "
              f"game is {args.game!r} — accepted anyway, but {first} is conventional here.",
              file=sys.stderr)
    elif "--white" in tokens and first != "--white":
        print(f"note: --white works for {args.game} too (same seat), but {first} is the "
              f"conventional spelling for this game.", file=sys.stderr)
    if "--blue" in tokens and second != "--blue":
        print(f"note: --blue is corewar's spelling of the second seat flag; "
              f"game is {args.game!r} — accepted anyway, but {second} is conventional here.",
              file=sys.stderr)
    elif "--black" in tokens and second != "--black":
        print(f"note: --black works for {args.game} too (same seat), but {second} is the "
              f"conventional spelling for this game.", file=sys.stderr)


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    warn_seat_flag_mismatch(args, argv)
    args.func(args)


if __name__ == "__main__":
    main()
